version: "3.8"

services:
  node_app:
    build: .
    networks:
      - app-network
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8000:8000
    env_file: .env

  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  stock-service:
    image: deliverymuch/backend-challenge:stock-service
    networks:
      - app-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - node_app
    links:
      - rabbitmq
    restart: on-failure
  postgres:
    image: "postgres:13"
    networks:
      - app-network
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge

volumes:
  my_dbdata: