version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    networks:
      - app-network
    ports:
      - 5672:5672
      - 15672:15672
  # stock-service:
  #   image: deliverymuch/backend-challenge:stock-service
  #   networks:
  #     - app-network
  #   environment:
  #     - RABBITMQ_URL=amqp://rabbitmq
  #   depends_on:
  #     - rabbitmq
  #   links:
  #     - rabbitmq
  #   restart: on-failure
  db:
    image: "postgres:13"
    container_name: "my_postgres"
    environment:
      POSTGRES_PASSWORD: "my_password"
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge

volumes:
  my_dbdata: